[package]
name = "learning-tools-interoperability"
description = "Tools and Structs for the Learning Tools Interoperability (LTI)"
edition = "2024"
homepage = "https://github.com/Ameelio/learning-tools-interoperability/"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Ameelio/learning-tools-interoperability/"
version = "0.1.0-alpha.1"

[features]
axum = [
  "dep:lti-launch"
]

[dependencies]
lti-launch = { version = "0.1.0", path = "../lti-launch", optional = true }
lti-spec = { version = "0.1.0", path = "../lti-spec"}
