[package]
name = "lti-claims"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
chrono.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_jwt.workspace = true
thiserror.workspace = true
tower.workspace = true
tracing.workspace = true
url.workspace = true

lti-spec = { path = "../lti-spec"}
