[package]
name = "lti-launch"
description = "Axum LTI Launch Handler"
edition = "2024"
homepage = "https://github.com/Ameelio/learning-tools-interoperability/"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Ameelio/learning-tools-interoperability/"
version = "0.1.0"

[dependencies]
axum.workspace = true
axum-extra.workspace = true
lti-spec = { version = "0.1.0", path = "../lti-spec"}
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
